#!/usr/bin/env perl 

## The sink we are interested in should be given as the 
## 1st argument to the script.
my $sink=$ARGV[0];

## If the script has been run with a second argument,
## that argument will be the volume threshold we are checking

## Run the pactl command and save the output in 
## ther filehandle $fh
open(my $fh, '-|', 'pactl list sinks');

## Set the record separator to consecutive newlines (same as -000)
## this means we read the info for each sink as a single "line".
$/="\n\n";

## Go through the pactl output
while (<$fh>) {
    ## If this is the sink we are interested in
    if (/#$sink/) {
        ## Extract the current colume of this sink
        /Volume:.*?(\d+)%/;
        my $volume=$1;
        if(/Mute\: yes/){
            print "Muted\n";
        }else{
        ## If the script has been run with a second argument,
        ## check whether the volume is above or below that
        ## Else, if the script has been run with just one argument,
        ## print the current volume.
            print "$volume%\n";
        }
    }#
}
