#!/bin/bash

#echo "{\"version\":1}"
echo "{ \"version\": 1, \"stop_signal\": 10, \"cont_signal\": 12, \"click_events\": true }"
echo "[[]"
conky -d 

IFS="}"
while read;do
    IFS=" "
    STR=`echo $REPLY | sed -e s/[{}]//g -e "s/ \"/\"/g" | awk '{n=split($0,a,","); for (i=1; i<=n; i++) {m=split(a[i],b,":"); if (b[1] == "\"name\"") {NAME=b[2]} if (b[1] =="\"x\"") {X=b[2]} if (b[1] =="\"y\"") {Y=b[2]} } print NAME " " X " " Y}'`
    read NAME X Y <<< $STR
    X=$(($X-50))
    case "${NAME}" in
        \"date\")
            yad --no-buttons --mouse --class "YADWIN" --calendar
            ;;
        \"temp\")
            yad --no-buttons --text-info --height 260 --width 500 --mouse  --class "YADWIN" --margins=10 --filename=<(acpi -V)
            ;;
        \"bright\")
            LEVEL=$(/home/joey/.bin/scripts/conky/blevel.sh)
            OUT=`yad --text="Brightness" --scale --value $LEVEL --button gtk-ok:0 --mouse --class "YADWIN" text-align center`
            if [[ $? -eq 0 ]];then
                /home/joey/.bin/scripts/conky/conkexec.sh light -S $OUT
            fi
            ;;
        \"volume\")
            VOL=$(/home/joey/.bin/scripts/conky/pacvol.sh display | sed "s/[^1-9]//" | sed "s/%//")
            OUT=`yad --text="Volume" --scale --value $VOL --button gtk-ok:0 --mouse --class "YADWIN" --text-align center`
            if [[ $? -eq 0 ]];then
                TARGET="$((655*$OUT))"
                /home/joey/.bin/scripts/conky/conkexec.sh pacmd set-sink-volume 0 $TARGET
            fi
            ;;
        *)
            ;;
    esac
    IFS="}"
done
