#!/bin/bash
# export DBUS_SESSION_BUS_ADDRESS environment variable because cron hates me
PID=$(pgrep -o gnome-session -u "joey")
export DBUS_SESSION_BUS_ADDRESS=$(sudo grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
TIME="$(date '+%H%M')"
echo "The current time is $TIME"

CIVS="$(/home/joey/.bin/scripts/day-night/find-twilight | cut -f1 -d\ )"
CIVE="$(/home/joey/.bin/scripts/day-night/find-twilight | cut -f2 -d\ )"
echo "Daylight starts at $CIVS ends at $CIVE"
if [ $TIME -ge $CIVS ] && [ $TIME -le $CIVE ] ; then
	echo "Switching to Day mode"
	RESP=exec /home/joey/.bin/scripts/day-night/day-mode
else
	echo "Switching to Night mode"
	RESP=exec /home/joey/.bin/scripts/day-night/night-mode
fi

if [[ $RESP ]] ; then
	echo "Switch failure"
else
	echo "Switch sucess"
fi
